dependency-dir: ./src/

source:
    - src/cmp/cmp.c
    - src/rate_limiter.c

target.arm:
    - src/syscalls.c
    - src/board.c
    - src/error.c
    - src/main.c
    - src/usbcfg.c
    - src/exti.c
    - src/sensors/mpu60X0.c
    - src/sensors/ms5611.c
    - src/sensors/hmc5883l.c
    - src/sensors/h3lis331dl.c
    - src/onboardsensors.c
    - src/sqrtpatch.c
    - src/shell_cmds.c
    - src/sumd_input.c
    - src/sdlog.c
    - src/stream.c
    - src/log.c
    - src/sdcard.c
    - src/datagram_message_comm.c
    - src/attitude_determination.cpp
    - src/flight-stack/src/attitude_estimation/ekf_gyro_acc.cpp
    - src/flight-stack/src/attitude_estimation/ekf_gyro_acc_mag.cpp

include_directories:
    - src/flight-stack/src/
    - src/eigen/

depends:
    - crc
    - serial-datagram:
        fork: stapelzeiger
    - math:
        fork: stapelzeiger
    - rcservo:
        fork: stapelzeiger
    - hott:
        fork: stapelzeiger
    - cmp_mem_access:
        fork: stapelzeiger
    - arm-cortex-tools
    - parameter
    - timestamp
    - datagram-messages

tests:
    - src/tests/rate_limiter_test.cpp

templates:
    Makefile.include.jinja: src/src.mk
