/* THIS FILE IS AUTOMATICALLY GENERATED */
#ifndef TEST_TYPE_H
#define TEST_TYPE_H

#include <stdint.h>
#include <msgbus/type_definition.h>


typedef struct {
    float x;
    int32_t y;
} simple_t;

typedef struct {
    simple_t s;
} nested_t;

/* msgbus type definitions */
extern const msgbus_type_definition_t simple_type;
extern const msgbus_type_definition_t nested_type;

#endif /* TEST_TYPE_H */