/* THIS FILE IS AUTOMATICALLY GENERATED */
#include <msgbus/type_definition.h>
#include "test.h"

static const msgbus_type_entry_t simple_entries[] = {
    {
        .name = "x",
        .is_base_type = 1,
        .is_array = 0,
        .is_dynamic_array = 0,
        .array_len = 0,
        .dynamic_array_len_struct_offset = 0,
        .struct_offset = offsetof(simple_t, x),
        .base_type = MSGBUS_TYPE_FLOAT32,
        .size = sizeof(float),
    },
    {
        .name = "y",
        .is_base_type = 1,
        .is_array = 0,
        .is_dynamic_array = 0,
        .array_len = 0,
        .dynamic_array_len_struct_offset = 0,
        .struct_offset = offsetof(simple_t, y),
        .base_type = MSGBUS_TYPE_INT32,
        .size = sizeof(int32_t),
    },
};

const msgbus_type_definition_t simple_type = {
    .hash = {0x82, 0x78, 0xd7, 0x20},
    .nb_elements = 2,
    .elements = simple_entries,
    .struct_size = sizeof(simple_t),
};

static const msgbus_type_entry_t nested_entries[] = {
    {
        .name = "s",
        .is_base_type = 0,
        .is_array = 0,
        .is_dynamic_array = 0,
        .array_len = 0,
        .dynamic_array_len_struct_offset = 0,
        .struct_offset = offsetof(nested_t, s),
        .type = &simple_type,
        .size = sizeof(simple_t),
    },
};

const msgbus_type_definition_t nested_type = {
    .hash = {0x4d, 0x58, 0x29, 0x81},
    .nb_elements = 1,
    .elements = nested_entries,
    .struct_size = sizeof(nested_t),
};
