#ifndef ROS_INTERFACE_COMM_MSG_H
#define ROS_INTERFACE_COMM_MSG_H


enum {
    ROS_INTERFACE_COMM_MSG_ID_HEARTBEAT=1,
    ROS_INTERFACE_COMM_MSG_ID_PING=2,
    ROS_INTERFACE_COMM_MSG_ID_PONG=3,
};


#endif /* ROS_INTERFACE_COMM_MSG_H */
