depends:
    - test-runner
    - cmp:
        fork: camgunz
    - cmp_mem_access

source:
    - msgbus.c
    - serialization_msgpack.c
    - type_print.c

tests:
    - tests/mocks/synchronization.cpp
    - tests/mocks/assert.cpp
    - tests/types/test.c
    - tests/atomicity.cpp
    - tests/bus_test.cpp
    - tests/topic_test.cpp
    - tests/subscriber_test.cpp
    - tests/signaling.cpp
    - tests/serialization_msgpack_test.cpp
    - tests/type_print_test.cpp
    - tests/cpp_wrapper_test.cpp

target.demo:
    - examples/posix/demo.c
    - examples/posix/messagebus_port.c
    - dependencies/cmp/cmp.c

templates:
    demo.jinja: CMakeLists.txt
